services:
  cadvisor:
    image: google/cadvisor
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    expose:
      - 8080
    ports:
      - "8005:8080"
    networks:
      - monitoring
  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - "9100:9100"
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge


# version: "3.7"
# services:
#   myapp:
#     image: $DOCKER_LOGIN/myapp:latest
  
#     deploy:
#       replicas: 3
#       placement:
#         constraints:
#           - node.role == worker
#       update_config:
#         parallelism: 2
#         delay: 10s
#     ports:
#       - "80:80"
#     networks:
#       - mynet
# networks:
#   mynet:



# version: '3'
# services:
#   web:
#     image: seckndanane/my-angular-app:latest
#     ports:
#       - "4200:4200"
#     environment:
#       - NG_APP_ENV=production
#     volumes:
#       - .:/app
#     command: "npm start"
