version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:16.10
        # auth:
        #     username: seckndanane
        #     password: Babacar98
    steps:
      - setup_remote_docker:
          version: 20.10.14
      - checkout
      - run: npm install
      - run: npm run build
      - run: npm test --watch=false
      - run: docker login -u seckndanane -p Babacar98
      - run: docker build -t my-angular-app .
      - run: docker tag my-angular-app seckndanane/my-angular-app
      - run: docker push seckndanane/my-angular-app
  deploy:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - run:
          name: Connect to Play with Docker via SSH
          command: |
            # Get the public IP address of the Play with Docker node
            export PWD_IP=$(ip a | grep 'inet ' | cut -d' ' -f6 | cut -d/ -f1)
            # Connect to the Play with Docker node via SSH
            ssh ip172-18-0-57-ceq26u791rrg00fasu0g
      - run:
          name: Deploy to Play with Docker
          command: |
            #Deploy the Docker image to the Play with Docker node
            docker run -p 8080:80 seckndanane/my-angular-app
      - run:
          name: Check deployment
          command: |
            # Check if the deployment was successful by accessing the application through the public IP address
            curl http://$PWD_IP:8080


# #This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
# version: 2.1

# # Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# # See: https://circleci.com/docs/2.0/orb-intro/
# orbs:
#   node: circleci/node@4.7

# # Invoke jobs via workflows
# # See: https://circleci.com/docs/2.0/configuration-reference/#workflows
# workflows:
#   sample: # This is the name of the workflow, feel free to change it to better match your workflow.
#     # Inside the workflow, you define the jobs you want to run.
#     jobs:
#       - node/test:
#           # This is the node version to use for the `cimg/node` tag
#           # Relevant tags can be found on the CircleCI Developer Hub
#           # https://circleci.com/developer/images/image/cimg/node
#           version: '16.10'
#           # If you are using yarn, change the line below from "npm" to "yarn"
#           pkg-manager: npm
# version: 2.1
# jobs:
#   build:
#     docker:
#       - image: node:latest
#     steps:
#       - checkout
#       - run: npm install
#       # - run: npm test
#       - run: npm run build




# version: 2.1

# jobs:
#   build:
#     steps:
#       - run:
#           name: Build and push Docker image
#           command: |
#             docker build -t my-image .
#             docker push my-image
#   deploy:
#     steps:
#       - run:
#           name: Deploy to Kubernetes
#           command: |
#             kubectl set image deployment/my-deployment my-container=my-image




# version: 2.1
# orbs:
#   browser-tools: circleci/browser-tools@1.2.3
# jobs:
#   build:
#     working_directory: ~/ng-project
#     docker:
#       - image: cimg/node:16.13.1-browsers
#     steps:
#       - browser-tools/install-chrome
#       - browser-tools/install-chromedriver
#       - run:
#           command: |
#             google-chrome --version
#             chromedriver --version
#           name: Check install
#       - checkout
#       - restore_cache:
#           key: ng-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
#       - run: npm install
#       - save_cache:
#           key: ng-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
#           paths:
#             - "node_modules"
#       - run: npm run build
#       # - run: npm run test